package main

// GlobalProductFactory contains the global display configuration
var GlobalProductFactory = newProductFactory()

// Product generated by one of the machines in the world
type Product struct {
	name           string
	productType    int
	representation rune
}

// ProductFactory factory for generating all the possible Products
type ProductFactory struct {
	products []*Product
}

// GetProduct returns the Product identified by the product id
func (pf *ProductFactory) GetProduct(id int) *Product {
	return pf.products[0]
}

func newProductFactory() *ProductFactory {
	pf := new(ProductFactory)
	pf.products = make([]*Product, 1)

	pf.products[0] = &Product{"copper", 0, 'c'}

	return pf
}
